include ../../config/Makefile.$(VENDOR)

# compile without opt:
CCFLAGSF= $(CCFLAGSG)
CCFLAGSO= $(CCFLAGSG)
CCFLAGS = $(CCFLAGSG)
FFLAGSF = $(FFLAGSG)
FFLAGSO = $(FFLAGSG)

all:
	bpp opcoeff.bf

clean:
	rm -f *.o

