# Make for the cmd directory to make it easier to re-make things in the parent directory

# test beam model:
tbm:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) tbm

# test boundary layer profile:
tblp:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) tblp

# test eye curves
eyeTest:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) eyeTest

# test RigidBodyMotion clas
trb:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) trb


# Here are targets to build grids for some of the examples. 
