# Make deforming ellipse grids


ogen = /home/henshw/Overture.g/bin/ogen


grids: deformingEllipseGrid

deformingEllipseGrid:
	$(ogen) -noplot deformingEllipseGrid -factor=2 -interp=e -width=.25
	$(ogen) -noplot deformingEllipseGrid -factor=4 -interp=e -width=.25
	$(ogen) -noplot deformingEllipseGrid -factor=8 -interp=e -width=.25
	$(ogen) -noplot deformingEllipseGrid -factor=16 -interp=e -width=.25

