#! /bin/csh -f
#  cp files into the Overture directory


# usage: build [overtureDirectory=$OvertureBuild]

if ($#argv != 1) then
  # default:
  set ovDir = $OvertureBuild
else
  set ovDir = $argv[1]
endif

echo "Copy the DataBase files into the $ovDir directory..."

# here is where the library is
set OvertureDB      = $ovDir/DataBase
set OvertureInclude = $ovDir/include

cp {GenericDataBase,HDF_DataBase,HDF5_DataBase,DataBaseBuffer,ListOfHDF_DataBaseRCData}.C             $OvertureDB
cp HDF5_DataBase.bC             $OvertureDB
cp {GenericDataBase,HDF_DataBase,HDF5_DataBase,DataBaseBuffer,ListOfHDF_DataBaseRCData}.h             $OvertureInclude

cp {thdf1.C,dbex1.C,dbex2.C,dbex2a.C} $ovDir/tests

# Kyle's DataBase routines:
cp {dbAccess.C,dbFunctions.f,kk_ptr.cc} $OvertureDB
cp {DBase.hh,kk_defines.hh,kk_ptr.hh} $ovDir/include

exit
