#! /bin/csh -f

# purify_bytes_potentially_leaked
# purify_access_errors
# purify_bytes_leaked

echo "Start of purify_check: searching for errors in all *.#.error files ..."

grep "bytes potentially leaked" *.error | grep -v "* 0 bytes potentially leaked"
grep "bytes leaked"             *.error | grep -v "* 0 bytes leaked"
grep "access errors"            *.error | grep -v "* 0 access errors, 0 total occurrences"

echo "End of purify_check: finished searching for errors"
