# Make for the cmd directory to make it easier to re-make things in the parent directory

cgmp:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) cgmp

mp:
	@cd ..;      $(MAKE) -$(MAKEFLAGS) mp

clean:
	rm -f *.log *.check *.debug *.move

