#!/bin/sh -f

# This script checks out A++P++ and builds the complete source code.

# You may want to do a simple redirection of stdout to get a
# log file, i.e. script_name > log_file.
# This scrip redirects stderr to stdout, so do not worry about
# redirecting stderr yourself.


short_name=`basename $0`	# The short name for this script.


# Set default flags for this script before processing script options.
top_dir='A++P++'
banner='echo'
export=checkout


# Start processing options for this script.
for optstr in "$@"; do
    # echo optstr: \"$optstr\"
    case "$optstr" in
	-h | -help | --help | --hel | --he )
	cat << EOF
Usage: $short_name [options]
  Options:
  -h, --help
	Print this message.
  -s, --show-self
	Shows (cat) this script.
  -n, --no-action
	Do not do anything.  Just list the commands that would be issued.
  -q, --quiet
	Do not output banner information.
  --cvs-tag=<cvs tag>
	Use the given <cvs tag> for cvs checkout.
  --top-dir=<directory>
	Check out the distribution into the given directory.
For your logging convenience, this script redirects stderr to stdout.
(Do not try to redirect stderr from this script because there is nothing left.)
EOF
	exit 0 ;;
	--cvs-tag=* )
	    cvs_tag=`echo $optstr | sed 's/[^=]*=//'`
	    # Here are some shorthand for the --cvs-tag flag.
	    if [ "$cvs_tag" = "6d" ]; then
		cvs_tag=BTNG~parti4Dto6D~00~000414~no-change-yet
	    fi
	    cvs_tag="-r $cvs_tag"
	;;
	--top-dir=* )
	    top_dir=`echo $optstr | sed 's/[^=]*=//'`
	    if [ -z "$top_dir" ]; then
		top_dir="A++P++"
	    fi
	;;
	-n | --no-action | --no-actio | --no-acti | --no-act | --no-ac | --no-a )
	action=echo
	;;
	-s | --show | --show-self )
	cat $0
	exit
	;;
	-q | --quiet | --quie | --qui | --qu | --q )
	banner=:
	;;
    esac
done
# echo cvs_tag is $cvs_tag
# Done processing options for this script.


CVSROOT=/usr/casc/overture/A++P++/A++P++CVS/A++P++_Repository


export banner action
grun () {
    $banner
    COM=$1
    BEGTIME=`date +%H:%M:%S`
    $banner "============================================================="
    $banner "STARTING \"$COM\" at $BEGTIME"
    $banner "============================================================="
    if [ -z "$action" ]; then
        eval $COM 2>&1
    else
        $action "$COM" 2>&1
    fi
    if [ $? != 0 ]; then
	echo Error running $COM
	exit 1
    fi
    $banner "============================================================="
    $banner "FINISHED $2: $BEGTIME to `date +%H:%M:%S`"
    $banner "============================================================="
}


$banner "executing:		$0"
$banner "from:			`pwd`"
$banner "on:			`uname -a`"
$banner "at:			`date`"
$banner "by:			\"`whoami`\""
$banner "CVSROOT is:		\"$CVSROOT\""
$banner "A++P++ tag is:		\"$cvs_tag\""
$banner "process id is:		$$"

M4=gm4
which $M4 > /dev/null 2>&1 || M4=m4

grun "cvs -d $CVSROOT checkout $cvs_tag -n -d $top_dir A++P++"	"cvs checkout"
grun "echo y | cvs -d $CVSROOT release $top_dir; echo"		"cvs release"
grun "cd $top_dir"						"cd A++P++"
grun "SCRIPTS/makelinks"					"makelinks"
grun "make -f makefile.build all_source M4=$M4"			"makefile.build all_source"
grun "./build"							"build"

$banner
$banner "============================================================="
$banner "$short_name DONE"
$banner "============================================================="

exit

