#! /bin/csh
# This is an example configuration line, the use can pick and choose among numerous 
# options to control the compilation process in A++/P++.  These are useful scripts
# which can be used as examples.

# These options with the configure script select option specific use of P++ on any 
# machine where the C compiler is called "cc" and the C++ compiler is called "CC".
# The autoconf mechanism automatically detects the machine type and sets other
# parameters as required.  In this example P++ is enabled.  Also, tests for shared
# libraries will be preformed (which is the default).

./configure --enable-PXX --enable-SHARED_LIBS --with-CC=cc --with-CXX=CC
