#! /bin/csh

# Verifies the source is build and builds the Makefile.depend files
SCRIPTS/makeSource

# move up from the A++P++/SCRIPTS directory to the A++P++ directory
# cd ..

# Make the object files and A++/P++ libraries
# make -d check
# echo "MAKE COMMENTED OUT\!"
make

# Run tests on newly built A++P++ libraries
# echo "make check commented out!"

# echo "MAKE CHECK COMMENTED OUT\!"
make check
