#! /bin/csh

# echo "makelinks build links to files that CVS does not support!"; \
# echo "     run by CVS upon checkout of A++P++ module cvs checkout A++P++"; \
# echo "     specified within A++P++_Repository/CVSROOT/modules"; \
# echo "     line in A++P++_Repository/CVSROOT/modules A++P++ -o A++P++/makelinks A++P++"; \

# Build links (some are required for the makefiles to work properly)
cd ..; A++P++/makelinks; cd A++P++

# Make absolutely all source code
make -f makefile.build

# Build links (likely this just rebuilds them)
# cd ..; A++P++/makelinks; cd A++P++

# run configure to build the config.h files in all the source directories
# so that depend files can be generated.
configure

# Build dependency files for make (these are build into the Makefile.in already
# so updating the Makefile.in would require calls to "build" before running
# configure.  Maybe we should not worry about generating Makefile.depend here
# and include it directly within the CVS respository.
make -f makefile.build depend





