#! /bin/csh

# find . -name config.cache -exec rm -rf {} \;
# find . -depth -print -exec ls -d {} \;

set cdir = `pwd`
# chmod a+x lib*.a lib*.so

# setup path in new shell
set path=(/home/dquinlan/A++P++/A++P++Source/A++P++ $path)

echo ""
echo "Removing the stamp-h files from the A++/P++ directory structure"
echo ""
# Delete the existing stamp-h files in the directory structure
find . -name stamp-h -exec rm -rf {} \;

# Add new stamp-h files in the directory structure
# foreach dir (*)
#   if( -d $dir ) then
#     echo "Adding timestamp (stamp-h) file to directory <$dir>"
#     echo timestamp > stamp-h
# #   chmod a+x lib*.a lib*.so 
# #   chmod a+x $dir
#     cd $dir
#    timeStampUpdate $dir
#    cd $cdir
#  endif
# end
