ogen = /home/henshw/Overture.g/bin/ogen

# generate some grids
grids : grids2d 

# 2D grids: 
grids2d:
	$(ogen) -noplot fallingBodyGrid -interp=e -order=2 -factor=2
	$(ogen) -noplot fallingBodyGrid -interp=e -order=2 -factor=4
	$(ogen) -noplot fallingBodyGrid -interp=e -order=2 -factor=8


