      real d12
      real d22
      real ur2
      real us2
      real ut2
      real urr2
      real uss2
      real urs2
      real utt2
      real urt2
      real ust2
      real urrr2
      real usss2
      real uttt2
      real rxr2
      real rxs2
      real rxt2
      real rxrr2
      real rxss2
      real rxrs2
      real ryr2
      real rys2
      real ryt2
      real ryrr2
      real ryss2
      real ryrs2
      real rzr2
      real rzs2
      real rzt2
      real rzrr2
      real rzss2
      real rzrs2
      real sxr2
      real sxs2
      real sxt2
      real sxrr2
      real sxss2
      real sxrs2
      real syr2
      real sys2
      real syt2
      real syrr2
      real syss2
      real syrs2
      real szr2
      real szs2
      real szt2
      real szrr2
      real szss2
      real szrs2
      real txr2
      real txs2
      real txt2
      real txrr2
      real txss2
      real txrs2
      real tyr2
      real tys2
      real tyt2
      real tyrr2
      real tyss2
      real tyrs2
      real tzr2
      real tzs2
      real tzt2
      real tzrr2
      real tzss2
      real tzrs2
      real ux21
      real uy21
      real uz21
      real ux22
      real uy22
      real uz22
      real ux23
      real uy23
      real uz23
      real rxx21
      real rxx22
      real rxy22
      real rxx23
      real rxy23
      real rxz23
      real ryx22
      real ryy22
      real ryx23
      real ryy23
      real ryz23
      real rzx22
      real rzy22
      real rzx23
      real rzy23
      real rzz23
      real sxx22
      real sxy22
      real sxx23
      real sxy23
      real sxz23
      real syx22
      real syy22
      real syx23
      real syy23
      real syz23
      real szx22
      real szy22
      real szx23
      real szy23
      real szz23
      real txx22
      real txy22
      real txx23
      real txy23
      real txz23
      real tyx22
      real tyy22
      real tyx23
      real tyy23
      real tyz23
      real tzx22
      real tzy22
      real tzx23
      real tzy23
      real tzz23
      real uxx21
      real uyy21
      real uxy21
      real uxz21
      real uyz21
      real uzz21
      real ulaplacian21
      real uxx22
      real uyy22
      real uxy22
      real uxz22
      real uyz22
      real uzz22
      real ulaplacian22
      real uxx23
      real uyy23
      real uzz23
      real uxy23
      real uxz23
      real uyz23
      real ulaplacian23
      real h12
      real h22
      real ux23r
      real uy23r
      real uz23r
      real uxx23r
      real uyy23r
      real uxy23r
      real uzz23r
      real uxz23r
      real uyz23r
      real ux21r
      real uy21r
      real uz21r
      real uxx21r
      real uyy21r
      real uzz21r
      real uxy21r
      real uxz21r
      real uyz21r
      real ulaplacian21r
      real ux22r
      real uy22r
      real uz22r
      real uxx22r
      real uyy22r
      real uzz22r
      real uxy22r
      real uxz22r
      real uyz22r
      real ulaplacian22r
      real ulaplacian23r
