eval 'exec perl -S $0 ${1+"$@"}'
if 0;
#!/usr/bin/perl
# perl program to configure Overture Makefiles

# perl program to create some operators

#  GenericCompositeGridOperators from GenericGridCollectionOperators 
#  CompositeGridOperators from GridCollectionOperators 
@filenames=("GenericGridCollectionOperators.h","GenericGridCollectionOperators.C", 
            "GridCollectionOperators.h","GridCollectionOperators.C");

foreach $file ( @filenames )
{
  $cgfile = $file;
  $cgfile =~ s/GridCollectionOperators/CompositeGridOperators/;
  open(FILE,"$file") || die "cannot open file $file!" ;
  open(FILEF,">$cgfile");

  print FILEF "// **** THIS FILE WAS AUTOMATICALLY GENERATED BY makeOperators.p from $file ******\n";
  while( <FILE> )
  {
      $line = $_;   
      $line =~ s/(GenericGridCollectionOperators)/GenericCompositeGridOperators/g;
      $line =~ s/(GridCollectionOperators)/CompositeGridOperators/g;
      $line =~ s/(GRID_COLLECTION_OPERATORS)/COMPOSITE_GRID_OPERATORS/g;
      $line =~ s/\b(realGridCollectionFunction)\b/realCompositeGridFunction/g;
      $line =~ s/\b(GridCollection)\b/CompositeGrid/g;
      $line =~ s/\b(GridCollectionData)\b/CompositeGridData/g;

      $line =~ s/\b(realGridCollectionFunctionReally)\b/realGridCollectionFunction/g;
      $line =~ s/\b(GridCollectionReally)\b/GridCollection/g;

      $line =~ s/^\/\/ define COMPOSITE_GRID_OPERATORS/\#define COMPOSITE_GRID_OPERATORS/g;

#      $line =~ s/\bCOMPOSITE_GRID\b/1/;  # for ifdef 

      $file = FILEF;
      # print "$type $file $line";
      print $file $line;
   } 
  close(FILE);

}


