#!/bin/sh -x

# $Id: preconf,v 1.3 2001/10/22 18:39:23 gunney Exp $

# This generates the aclocal.m4 file.
# aclocal grabs macros an put it in aclocal.m4
aclocal -I .

# This generates configure
autoconf

# This generates config.h.in
autoheader

# This generates Makefile.in and stamp-h.in
# The -a flag tells automake to generate missing files
# it will need, such as COPYING, install.sh, etc.
# The -c flag copies instead of link to the missing files.
automake -a -c
