// File generated by overtureFramework/cg/mx/codes/manufacturedPulse.maple
// Ex = -(-cy*t+y-y0)*amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2))
// Ey = (-cx*t+x-x0)*amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2))
// Hz = amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2))
real t2,t3,t5,t6,t9,PSI,t14,t16,t19,t20,t21,t23,t25,t27,t28,t30,t32,t35,t36,t38,t40,t41,t45,t46,t47,t54,t49,t61,t68,FEX,FEY,FHZ;
t2 = -cx * t + x - x0;
t3 = t2 * t2;
t5 = -cy * t + y - y0;
t6 = t5 * t5;
t9 = exp(-beta * (t3 + t6));
PSI = amp * t9;
t14 = -0.2e1 * t2 * cx - 0.2e1 * t5 * cy;
t16 = beta * t14 * t9;
t19 = t5 * amp;
t20 = cx * cx;
t21 = cy * cy;
t23 = 0.2e1 * t20 + 0.2e1 * t21;
t25 = beta * t23 * t9;
t27 = beta * beta;
t28 = t14 * t14;
t30 = t27 * t28 * t9;
t32 = beta * t9;
t35 = 0.2e1 * t2;
t36 = t35 * t35;
t38 = t27 * t36 * t9;
t40 = amp * beta;
t41 = 0.2e1 * t5;
t45 = t41 * t41;
t47 = t27 * t45 * t9;
FEX = -0.2e1 * cy * amp * t16 + t19 * t25 - t19 * t30 - cSq * (0.2e1 * t40 * t41 * t9 + 0.4e1 * t19 * t32 - t19 * t38 - t19 * t47);
t54 = t2 * amp;
FEY = 0.2e1 * cx * amp * t16 - t54 * t25 + t54 * t30 - cSq * (-0.2e1 * t40 * t35 * t9 - 0.4e1 * t54 * t32 + t54 * t38 + t54 * t47);
t68 = amp * t27;
FHZ = -t40 * t23 * t9 + t68 * t28 * t9 - cSq * (t68 * t36 * t9 + t68 * t45 * t9 - 0.4e1 * t40 * t9);

