// File generated by overtureFramework/cg/mx/codes/manufacturedPulse.maple
// Ex = (cy*t-cz*t-y+y0+z-z0)*amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2+(-cy*t+z-z0)^2))
// Ey = (-cx*t+cz*t+x-x0-z+z0)*amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2+(-cy*t+z-z0)^2))
// Ez = (cx*t-cy*t-x+x0+y-y0)*amp*exp(-beta*((-cx*t+x-x0)^2+(-cy*t+y-y0)^2+(-cy*t+z-z0)^2))
real t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46,t47,t48,t49,t50,t51,t52,t53,t54,t55,t56,t57,t58,t59,t60,t61,t62,t63,t64,t65,t66,t67,t68,t69,t70,t71,t72,t73,t74,t75,t76,t77,t78,t79,t80,t81,t82,t83,t84,t85,t86,t87,t88,t89,t90,t91,t92,t93,t94,t95,t96,t97,t98,t99;
real PSI,FEX,FEY,FEZ;
t1 = cx * t;
t2 = -t1 + x - x0;
t3 = t2 * t2;
t4 = cy * t;
t5 = -t4 + y - y0;
t6 = t5 * t5;
t7 = -t4 + z - z0;
t8 = t7 * t7;
t11 = exp(-beta * (t3 + t6 + t8));
PSI = amp * t11;
t18 = -0.2e1 * t2 * cx - 0.2e1 * t5 * cy - 0.2e1 * t7 * cy;
t20 = beta * t18 * t11;
t23 = cz * t;
t25 = (t4 - t23 - y + y0 + z - z0) * amp;
t26 = cx * cx;
t28 = cy * cy;
t32 = beta * (0.2e1 * t26 + 0.4e1 * t28) * t11;
t34 = beta * beta;
t35 = t18 * t18;
t37 = t34 * t35 * t11;
t39 = beta * t11;
t42 = 0.2e1 * t2;
t43 = t42 * t42;
t45 = t34 * t43 * t11;
t47 = amp * beta;
t48 = 0.2e1 * t5;
t51 = 0.2e1 * t47 * t48 * t11;
t52 = t48 * t48;
t54 = t34 * t52 * t11;
t56 = 0.2e1 * t7;
t59 = 0.2e1 * t47 * t56 * t11;
t60 = t56 * t56;
t62 = t34 * t60 * t11;
FEX = -0.2e1 * (cy - cz) * amp * t20 - t25 * t32 + t25 * t37 - cSq * (-0.6e1 * t25 * t39 + t25 * t45 + t54 * t25 + t25 * t62 + t51 - t59);
t71 = (-t1 + t23 + x - x0 - z + z0) * amp;
t76 = 0.2e1 * t47 * t42 * t11;
FEY = -0.2e1 * (-cx + cz) * amp * t20 - t71 * t32 + t71 * t37 - cSq * (-0.6e1 * t71 * t39 + t71 * t45 + t71 * t54 + t71 * t62 + t59 - t76);
t89 = (t1 - t4 - x + x0 + y - y0) * amp;
FEZ = -0.2e1 * (cx - cy) * amp * t20 - t89 * t32 + t89 * t37 - cSq * (-0.6e1 * t89 * t39 + t89 * t45 + t89 * t54 + t89 * t62 - t51 + t76);

