! This file was generated by fib/codes/inviscid/exact.maple
! Exact solution for an inviscid incompressible flow and an Acoustic bulk solid

! ---------------------------------------------------------------------------------- 
! wr,wi  (input) : real and imag parts of omega. 
! rho,mu,H  (input) : fluid parameters. 
! rhos,cp,cs,Hs (input) : solid parameters. 
! detr,deti (output) real and imag parts of the dispersion relation (determinant).
! ---------------------------------------------------------------------------------- 
      subroutine dispersionInviscidAcoustic(wr,wi, detr,deti,
     &               rho,mu,H,k,rhos,cp,cs,Hs )
      implicit none 
      complex II,w,as,det,Cas,Sas
      complex a11,a12, a21,a22 
      complex aH,asHs,z,cosh,sinh 
      real rho,mu,H,k,rhos,Hs,cp,rcp2,cs,rcs2,u1Varies
      real wr,wi,detr,deti,Ck,Sk,lambdas,mus
      ! cosh(z) =(exp(z)+exp(-z))*.5
      ! sinh(z) =(exp(z)-exp(-z))*.5
      cosh(z) = cmplx(dcosh(real(z))*cos(imag(z)),
     &                dsinh(real(z))*sin(imag(z)))
      sinh(z) = cmplx(dsinh(real(z))*cos(imag(z)),
     &                dcosh(real(z))*sin(imag(z)))
      w=cmplx(wr,wi)
      rcp2=rhos*cp**2
      II=(0.,1.)
      Ck=dcosh(k*H)
      Sk=dsinh(k*H)
      as = sqrt(k ** 2 - w ** 2 / cp ** 2)
      asHs=as*Hs
      Cas=cosh(asHs)
      Sas=sinh(asHs)
      a11 = Sk
      a12 = -II * w * Sas
      a21 = II * rho * w / k * Ck
      a22 = rcp2 * as * Cas
      det = a11 * a22 - a12 * a21
      detr=real(det)
      deti=imag(det)
      return
      end

! 
! ---------------------------------------------------------------------------------- 
! wr,wi  (input) : real and imag parts of omega. 
! rho,mu,H  (input) : fluid parameters. 
! rhos,cp,cs,Hs (input) : solid parameters. 
! dwr,dwi (output) real and imag parts of d(det)/d(w), det=dispersion relation.
! ---------------------------------------------------------------------------------- 
      subroutine dispersionInviscidAcousticDeriv(wr,wi, dwr,dwi,
     &             rho,mu,H,k,rhos,cp,cs,Hs )
      implicit none 
      complex II,w,G,a,as,asHs,dw,Ca,Sa,Cas,Sas,dadw,dasdw,dw0,dw1 
      complex bs,Cbs,Sbs,dbsdw,bsHs 
      complex dCadw,dSadw,dCasdw,dSasdw,aH,z,cosh,sinh,dCbsdw,dSbsdw 
      complex a11,a12, a21,a22 
      complex da11,da12, da21,da22 
      real rho,mu,H,k,rhos,Hs,cp,rcp2,cs,rcs2
      real wr,wi, dwr,dwi,Ck,Sk,lambdas,mus
      ! cosh(z) =(exp(z)+exp(-z))*.5
      ! sinh(z) =(exp(z)-exp(-z))*.5
      cosh(z) = cmplx(dcosh(real(z))*cos(imag(z)),
     &                dsinh(real(z))*sin(imag(z)))
      sinh(z) = cmplx(dsinh(real(z))*cos(imag(z)),
     &                dcosh(real(z))*sin(imag(z)))
      w=cmplx(wr,wi)
      rcp2=rhos*cp**2
      II=(0.,1.)
      Ck=dcosh(k*H)
      Sk=dsinh(k*H)
      as = sqrt(k ** 2 - w ** 2 / cp ** 2)
      asHs=as*Hs
      Cas=cosh(asHs)
      Sas=sinh(asHs)
      dCasdw = Sas * Hs * dasdw
      dasdw = -w / cp ** 2 / as
      dCasdw = Sas * Hs * dasdw
      dSasdw = Cas * Hs * dasdw
      ! Note: daij = d(aij)/d(w)
      a11 = Sk
      da11 = 0
      a12 = -II * w * Sas
      da12 = -II * Sas - II * w * dSasdw
      a21 = II * rho * w / k * Ck
      da21 = II * rho / k * Ck
      a22 = rcp2 * as * Cas
      da22 = rcp2 * Cas * dasdw + rcp2 * as * dCasdw
      dw = da11 * a22 - a12 * da21 + a11 * da22 - da12 * a21
      dwr=real(dw)
      dwi=imag(dw)
      return
      end
